development:
  adapter: mysql2
  database: meteor_tracker_dev
  encoding: utf8
  host: localhost
  port: 3306
  username: arthwood
  password: asdf1234
test:
  adapter: mysql2
  database: meteor_tracker_test
  encoding: utf8
  host: localhost
  port: 3306
  username: arthwood
  password: asdf1234
